image:
  file: .gitpod.Dockerfile # Pastikan file ini ada di root repo

tasks:
  - name: Angular & Cypress Setup
    init: |
      echo "Starting Prebuild..."

      cd /workspace/learn-angular-sample/my-app
      echo "Current directory (init): $(pwd)" 
      echo "Listing files in current directory:"
      ls -la 
      echo "Running npm install in $(pwd)..."
      npm install 

      echo "Prebuild finished."
    command: |
      echo "Starting Workspace..."

      cd /workspace/learn-angular-sample/my-app
      echo "Current directory (command): $(pwd)" 

      echo "Running ng serve in $(pwd)..."

      npx ng serve --host 0.0.0.0 --disable-host-check &

      gp ports await 4200
      echo "Angular development server is running on port 4200."
      echo "=========================================================="
      echo "To open the Cypress Test Runner, run this in a NEW terminal:"

      echo "cd /workspace/learn-angular-sample/my-app && npx cypress open"
      echo ""
      echo "To run Cypress tests headlessly, run in a NEW terminal:"

      echo "cd /workspace/learn-angular-sample/my-app && npx cypress run"
      echo "=========================================================="
      # gp sync-done setup

ports:
  - port: 4200
    onOpen: open-preview
    name: Angular App (my-app)
    description: Angular Development Server
  - port: 6080
    onOpen: ignore
    name: VNC Interface
  - port: 5900
    onOpen: ignore
    name: VNC Port

vscode:
  extensions:
    - angular.ng-template
    - cypress.io
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker
